name: Execute Maven Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      - run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "artifactVersion=$VERSION" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v3
        with:
          path: target/push-client-java-${{ env.artifactVersion }}.jar
      - uses: actions/upload-artifact@v3
        with:
          path: target/push-client-java-${{ env.artifactVersion }}-javadoc.jar