name: Bump Version for next Release
on:
  workflow_call:
    inputs:
      type:
        description: The type of bump (major, minor, patch)
        type: string
        required: true
  workflow_dispatch:
    inputs:
      type:
        description: The type of bump (major, minor, patch)
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
jobs:
  bump-version:
    name: Bump Version and write it back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - run: |
          BRANCH=$( echo $GITHUB_REF | cut -d'/' -f 3 )
          echo "branch=$BRANCH" >> $GITHUB_ENV
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "artifactVersion=$VERSION" >> $GITHUB_ENV
      - name: Bump Version
        id: bump-version
        uses: SAP/java-integration-for-sap-mobile-services@actions_bump-version
        with:
          current-version: ${{ env.artifactVersion }}
          type: ${{ inputs.type }}
          is-dev: true
      - name: Update Version
        env:
          NEXT_VERSION: ${{ steps.bump-version.outputs.target-version }}
        run: |
          mvn -B --file pom.xml -DnewVersion="${NEXT_VERSION}" -DgroupId=\* -DartifactId=\* -DoldVersion=\* -DgenerateBackupPoms=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn org.codehaus.mojo:versions-maven-plugin:2.7:set
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: 'Bump version to ${{ steps.bump-version.outputs.target-version }}'
          committer: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          title: 'Bump version to ${{ steps.bump-version.outputs.target-version }}'
          body: |
            Bump project version to ${{ steps.bump-version.outputs.target-version }} in main branch for the next release
          labels: |
            automation
          base: ${{ env.branch }}
          branch-suffix: short-commit-hash
          delete-branch: true
      - name: Enable Automerge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: rebase
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

