name: Bump Version for next Release
on:
  workflow_dispatch:
    inputs:
      type:
        description: The type of bump (major, minor, patch)
        type: choice
        required: true
        options:
          - major
          - minor
          - patch
jobs:
  bump-version:
    name: Bump Version and write it back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - run: |
          BRANCH=$( echo $GITHUB_REF | cut -d'/' -f 3 )
          echo "branch=$BRANCH" >> $GITHUB_ENV
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "artifactVersion=$VERSION" >> $GITHUB_ENV
      - name: Bump Version
        id: bump-version
        uses: SAP/java-integration-for-sap-mobile-services@actions_bump-version
        with:
          current-version: ${{ env.artifactVersion }}
          type: ${{ inputs.type }}
      - name: Update Version
        env:
          NEXT_VERSION: ${{ steps.bump-version.outputs.target-version }}
        run: |
          mvn -B --file pom.xml -DnewVersion='${NEXT_VERSION}' -DgroupId=\\* -DartifactId=\\* -DoldVersion=\\* -DgenerateBackupPoms=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn org.codehaus.mojo:versions-maven-plugin:2.7:set
      - name: Commit Changes
        env:
          BUMP_COMMIT_MESSAGE: 'Set version to ${{ steps.bump-version.outputs.target-version }}'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com" 
          git config user.name "github-actions[bot]" 
          git add .
          git commit -m "$BUMP_COMMIT_MESSAGE"
          git remote rm origin
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
      - name: Push Changes to Temporary Release Branch
        env:
          TMP_BRANCH: release-preparation/${{ steps.bump-version.outputs.target-version }}
        run: |        
          git checkout -b ${TMP_BRANCH}
          git push origin ${TMP_BRANCH}
      - name: Push Changes to Main Branch
        if: ${{ env.branch == 'main' }}
        run: |
          git push origin main
      - name: Copy to Release Branch
        uses: SAP/java-integration-for-sap-mobile-services@actions_copy-to-release-branch
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch: ${{ steps.bump-version.outputs.target-branch }}
          current-branch: release-preparation/${{ steps.bump-version.outputs.target-version }}

