name: Prepare branch for a patch release
on:
  workflow_dispatch:
    {}
jobs:
  prepare-patch-release:
    name: Create a release for a patch release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "artifactVersion=$VERSION" >> $GITHUB_ENV
      - name: Bump Version
        id: bump-version
        uses: SAP/java-integration-for-sap-mobile-services@actions_bump-version
        with:
          current-version: ${{ env.artifactVersion }}
          type: patch
          is-dev: true
      - name: Update Version
        env:
          NEXT_VERSION: ${{ steps.bump-version.outputs.target-version }}
        run: |
          mvn -B --file pom.xml -DnewVersion="${NEXT_VERSION}" -DgroupId=\* -DartifactId=\* -DoldVersion=\* -DgenerateBackupPoms=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn org.codehaus.mojo:versions-maven-plugin:2.7:set
      - name: Commit Changes
        env:
          BUMP_COMMIT_MESSAGE: 'Bump version to ${{ steps.bump-version.outputs.target-version }}'
          BRANCH_NAME: ${{ steps.bump-version.outputs.target-branch }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com" 
          git config user.name "github-actions[bot]" 
          git add .
          git commit -m "$BUMP_COMMIT_MESSAGE"
          git remote rm origin
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
